#include "ICACHE.h"

void ICACHE_Init(void)
{
	ICACHE->CR &= ~ICACHE_CR_EN;
	ICACHE->CR |= ICACHE_CR_CACHEINV;
	while(!(ICACHE->SR & ICACHE_SR_BUSYF));
	ICACHE->CR |= ICACHE_CR_MISSMRST | ICACHE_CR_HITMRST;
	ICACHE->CR |= ICACHE_CR_MISSMEN | ICACHE_CR_HITMEN;
	ICACHE->CR |= ICACHE_CR_EN;
}
